branches:
  - name: "main"
  - name: "+([0-9])?(.{+([0-9]),x}).x"
    prerelease: false
  - name: "beta"
    prerelease: true
  - name: "alpha"
    prerelease: true
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: angular
      releaseRules:
        - type: feat
          release: minor
        - type: fix
          release: patch
        - type: refactor
          release: patch
        - type: ci
          release: patch
        - type: docs
          release: patch
        - type: test
          release: false
        - type: chore
          release: false
      parserOpts:
        noteKeywords:
          - BREAKING CHANGE
          - BREAKING CHANGES
          - BREAKING
  - - "@semantic-release/release-notes-generator"
    - preset: conventionalcommits
      presetConfig:
        types:
          - type: feat
            section: ":sparkles: Features"
            hidden: false
          - type: fix
            section: ":bug: Bug Fixes"
            hidden: false
          - type: refactor
            section: ":zap: Refactor"
            hidden: false
          - type: ci
            section: ":repeat: CI"
            hidden: false
          - type: test
            section: ":white_check_mark: Tests"
            hidden: false
          - type: docs
            section: ":memo: Documentation"
            hidden: false
          - type: chore
            hidden: true
      parserOpts:
        noteKeywords:
          - BREAKING CHANGE
          - BREAKING CHANGES
          - BREAKING
  - - "@semantic-release/exec"
    - verifyReleaseCmd: "echo ${nextRelease.version} > VERSION.txt"
  - - "@semantic-release/changelog"
    - changelogFile: CHANGELOG.md
  - "@semantic-release/gitlab"
